# Generated by Django 4.1.3 on 2022-11-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBrandApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
